### ISSUE TITLE
HELP! How to update cef browser to version 68

### ISSUE THREAD

**Issue by Jgaleas7** [nrkno/tv-automation-casparcg-server#16]
I want to update cef browser to version 68, is this possible?

**Comment by Julusian** [comment]
Updating the version of CEF requires compiling casparcg from source, but if you are comfortable doing that:

1) Replace the correct platform folder in https://github.com/nrkno/tv-automation-casparcg-server/tree/2.1.x/dependencies64/cef with a new copy from http://opensource.spotify.com/cefbuilds/index.html
1) There will likely be some very minor build issues in html_producer.cpp that will need resolving
1) Compile and it should all be good to go :)

**Comment by Jgaleas7** [comment]
when I have multiples pages, I can't separate audios for diferents chanels.

**Comment by Julusian** [comment]
This is a known issue and current limitation in CEF https://github.com/CasparCG/server/issues/669

It looks like it should be manageable with one of the next couple of releases of CEF, but there is no timeframe on when any version of caspar will support it.
