### ISSUE TITLE
system memory is not clearing after using frame_delay

### ISSUE THREAD

**Issue by sirfnomi** [nrkno/tv-automation-casparcg-server#22]
if suppose with `play 1-1 amb frame_delay 250` server is buffering in system memory (approximately 1GB) then after uninitialized current producer like (stop 1-1 , clear 1 or play another file) server is not clearing system memory of 1GB.
we must have to shutdown server for clearing memory

Specs:
Server 2.1.6
Windows 7, 10

**Comment by Julusian** [comment]
I think this is happening because memory for frames get reused due to allocation being costly. So after being allocated for the delay, the pool of available frames ends up being very large.
Technically this behaviour is by design, but I can see that in your case it has a rather large effect for no real benefit

**Comment by sirfnomi** [comment]
ahh ok so is there any short way to clear/flush this memory instead of shutting down whole server ?

**Comment by Julusian** [comment]
Could you try this with the official 2.1beta2, and run the `GL GC` AMCP command. It is currently disabled in this version, but I have no problem re-enabling if it will help with your use case

**Comment by sirfnomi** [comment]
yes, GC working in Server 2.1 beta2. will you please re-enable it in this version because it is useful for working with many delay frames

**Comment by Julusian** [comment]
Yes, it shall be back in the next version. Hopefully I will be able to release that before the end of the week.

**Comment by sirfnomi** [comment]
Thank You Julusian :)
