### ISSUE TITLE
Texture Sharing Support 

### ISSUE THREAD

**Issue by sirfnomi** [nrkno/tv-automation-casparcg-server#37]
Hi, 
are we getting [Texture Sharing Support](https://github.com/CasparCG/server/pull/1217)  in NRK builds ?

Thanks

**Comment by Julusian** [comment]
Yes, it is already merged in just waiting for the 2.1.11 release to become available

**Comment by sirfnomi** [comment]
Oh great !!
Thank You 😊

**Comment by sirfnomi** [comment]
If you don't mind will you please update that when we can expect version 2.1.11 to be released ??

**Comment by Julusian** [comment]
I want to get https://github.com/nrkno/tv-automation-casparcg-server/pull/36 tested and merged first, which I hope we can get done on monday, so it should be possible to get it released monday or tuesday

**Comment by sirfnomi** [comment]
Great !! 
Thanks Julusian

**Comment by Julusian** [comment]
2.1.11 has just been published https://github.com/nrkno/tv-automation-casparcg-server/releases/tag/v2.1.11_NRK

**Comment by sirfnomi** [comment]
Thanks Julusian ,
HTML performance is very smooth now 😊
