### ISSUE TITLE
Intel HD graphics rendering bug

### ISSUE THREAD

**Issue by olzzon** [nrkno/tv-automation-casparcg-server#4]
Just to inform. It looks like the bug mentioned here:
https://github.com/CasparCG/Server/issues/599
is in NRK 2.1 RC2

Running on Win-10 with a Intel HD630 
But I´ll just put a card in the machine.
:)

**Comment by baltedewit** [comment]
Strange... I don't have this issue on my i7-7700HQ. Is this on latest graphics drivers?

**Comment by olzzon** [comment]
Just upgraded the Drivers, and now it´s gone. Thanks.
And it´s still in the CG Client 2.0.8, so I´m quite sure the server runs correctly now
👍 
<img width="889" alt="skaermbillede 2018-08-29 kl 14 28 50" src="https://user-images.githubusercontent.com/29782499/44787735-378a7680-ab98-11e8-8cea-8f167fd0dfa1.png">

**Comment by Julusian** [comment]
I can't remember if there was a fix upstream made for this, or if it went away with driver updates. Anyone remember?

@olzzon The thumbnail previews shown in the client are cached. If you delete the contents of the thumbnail folder in the server folder it should regenerate them correctly

**Comment by olzzon** [comment]
Thanks for the help.
I close the Issue, as it was related to a driver update
👍
