### ISSUE TITLE
cinf return wrong data of duration of video

### ISSUE THREAD

**Issue by Jgaleas7** [nrkno/tv-automation-casparcg-server#8]
when I try this /cinf/ return wrong duration data.

Tested with 2.1.3_NRK server

Tested with media scanner v1.1.2-nrkno

**Comment by Julusian** [comment]
Do you mean the `CINF` AMCP command is returning the wrong value, or the `/cinf` http endpoint from the scanner? This version of caspar does not use the scanner for clip info.

**Comment by Jgaleas7** [comment]
Both,  the CINF AMCP command is returning the wrong value in duration. when I use 
const getVideo=await connectionCg.cinf('AMB')  return 268 of duration. but the video duration is 10 seconds.

TESTED with promise and Async/await. 

Idont know how to resolve this. HELP

**Comment by Jgaleas7** [comment]
Hi @Julusian ,

i would that amcp return total frames and duration in seconds. 
/cinf/
{
...
seconds: '10.72'
}
